title: <p align="center"> Linh Pham </p>

logo: "/images/avatar2.png"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/linhlhpham/">LinkedIn</a> |
  <a href="https://github.com/linhlhpham/">GitHub</a>
  </p>
  
  <p align="justify">
  I'm a motivated analytics professional with a deep passion for unraveling insights from data. I've successfully applied data-driven solutions to address complex challenges and optimize business performance.
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
