title: <p align="center"> Linh Pham </p>

logo: "/images/avatar2.png"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/linhlhpham/">LinkedIn</a> |
  <a href="https://github.com/linhlhpham/">GitHub</a>
  </p>
  
  <p align="left">
  I'm a motivated analytics professional with a deep passion for unraveling insights from data. I've successfully applied data-driven solutions to address complex challenges and optimize business performance.
  <br><br>
  Currently, I'm pursuing a Master of Science in Business Analytics at the University of Southern California, Marshall School of Business.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
